<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\Images\logo.png" />
    <Resource Include="Assets\Images\chatgpt_space_bg.png" />
    <Resource Include="Assets\Images\Icons\workorders.png" />
    <Resource Include="Assets\Images\Avatars\avatar_*.jpg" />
    <Resource Include="Themes\RunBookTheme.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>
</Project>
